version: '3.9'
services:
  database:
    container_name: database_api_vendas
    build:
      context: postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: vendas 
      POSTGRES_PASSWORD: vendas@123!#
    ports:
      - "5432:5432"
  api:

    container_name: api_vendas
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - database