version: '3.8'  
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1D5s6d1s51@521
    volumes:
      - ./src/shared/typeorm/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
